---
platform:
  os: linux
  arch: amd64

# Begin
clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "casperlabs/clarity-build:latest"

kind: pipeline
type: docker
name: build-publish

steps:
- name: make-test
  image: "casperlabs/clarity-build:latest"
  commands:
    - "make setup"
    - "make test"

- name: build-docker-image
  image: "casperlabs/clarity-build:latest"
  commands:
    - "make setup"
    - "export DOCKER_TAG=DRONE-${DRONE_BUILD_NUMBER}"
    - "make docker-build-all"
  volumes:
    - name: docker_sock
      path: "/var/run/docker.sock"

- name: docker-publish
  commands:
  - |
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      docker tag casperlabs/explorer:DRONE-${DRONE_BUILD_NUMBER} casperlabs/explorer:latest
      docker tag casperlabs/event-handler:DRONE-${DRONE_BUILD_NUMBER} casperlabs/event-handler:latest
      docker tag casperlabs/event-web-server:DRONE-${DRONE_BUILD_NUMBER} casperlabs/event-web-server:latest
      docker push casperlabs/explorer:latest
      docker push casperlabs/event-handler:latest
      docker push casperlabs/event-web-server:latest
  image: "casperlabs/clarity-build:latest"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
    - name: docker_sock
      path: "/var/run/docker.sock"
  when:
    event:
    - push
    branch:
    - master

volumes:
- name: docker_sock
  host:
    path: "/var/run/docker.sock"

trigger:
  event:
  - pull_request
  - push
  branch:
  - master
  - trying
  - staging
  - "FEAT-*"
  - "feat-*"
  - "feature-*"
  - "FEATURE-*"

---
kind: pipeline
type: docker
name: failed-build-alert

clone:
  disable: true

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    template:
    - |
      clarity build status: *{{ uppercasefirst build.status }}*
      Author: {{ build.author }}
      Drone Build: <{{ build.link }}|#{{ build.number }}>
      Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
  - failure
  branch:
  - dev
  - master
  - trying
  - staging
  - "FEAT-*"
  - "feat-*"
  - "feature-*"
  - "FEATURE-*"

depends_on:
- build-publish


---
kind: pipeline
type: docker
name: sdk-publish-tag

steps:
- name: sdk-pre-publish
  image: "casperlabs/clarity-build:latest"
  commands:
  - "yarn install"
  - "cd packages/sdk"
  - "npm run-script prepublishOnly"

- name: sdk-publish
  image: plugins/npm
  failure: "ignore"
  settings:
    username:
      from_secret: npm_user
    token:
      from_secret: npm_token
    email:
      from_secret: npm_email
    folder:
    - "packages/sdk"
    fail_on_version_conflict:
    - true
    access:
    - "public"

trigger:
  ref:
  - refs/tags/sdk*
