FROM node:12.5.0-stretch-slim

WORKDIR /app
ENV NODE_ENV=production

COPY package.json lerna.json /app/

# Application Packages
ADD packages /app/packages
ADD node_modules /app/node_modules

ARG CHAIN_NAME=delta-11
ENV CHAIN_NAME=$CHAIN_NAME

# The name display in the header of clarity
ARG NETWORK_NAME=delta-11
ENV NETWORK_NAME=$NETWORK_NAME

ARG FAUCET_ACCOUNT_PRIVATE_KEY_PATH=/app/packages/server/faucet-keys/private.key
ENV FAUCET_ACCOUNT_PRIVATE_KEY_PATH=$FAUCET_ACCOUNT_PRIVATE_KEY_PATH

ARG FAUCET_ACCOUNT_PUBLIC_KEY_PATH=/app/packages/server/faucet-keys/public.key
ENV FAUCET_ACCOUNT_PUBLIC_KEY_PATH=$FAUCET_ACCOUNT_PUBLIC_KEY_PATH

ARG SERVER_PORT=8001
ENV SERVER_PORT=$SERVER_PORT

ARG JSON_RPC_URL
ENV JSON_RPC_URL=$JSON_RPC_URL

ARG REACT_APP_EVENT_STORE_URL=http://localhost:3000
ENV REACT_APP_EVENT_STORE_URL=$REACT_APP_EVENT_STORE_URL

ARG UI_GRPC_URL=http://localhost:8081/rpc
ENV UI_GRPC_URL=$UI_GRPC_URL

ARG PAYMENT_AMOUNT=10000000
ENV PAYMENT_AMOUNT=$PAYMENT_AMOUNT

ARG TRANSFER_AMOUNT=100000000000
ENV TRANSFER_AMOUNT=$TRANSFER_AMOUNT

ARG GAS_PRICE=10
ENV GAS_PRICE=$GAS_PRICE

ARG NO_FAUCET=0
ENV NO_FAUCET=$NO_FAUCET

ARG WITH_LEDGER=0
ENV WITH_LEDGER=$WITH_LEDGER

ARG WITH_CSPR_LIVE_NOTICE=1
ENV WITH_CSPR_LIVE_NOTICE=$WITH_CSPR_LIVE_NOTICE

ARG CSPR_LIVE_NAME="CSPR Live"
ENV CSPR_LIVE_NAME=$CSPR_LIVE_NAME

ARG CSPR_LIVE_URL=https://cspr.live
ENV CSPR_LIVE_URL=$CSPR_LIVE_URL

ARG CLARITY_URL=https://clarity.make.services
ENV CLARITY_URL=$CLARITY_URL

ARG TRANSFER_COST=10000
ENV TRANSFER_COST=$TRANSFER_COST

ARG TRANSFER_MIN_AMOUNT=2500000000
ENV TRANSFER_MIN_AMOUNT=$TRANSFER_MIN_AMOUNT

ARG DELEGATE_COST=10000
ENV DELEGATE_COST=$DELEGATE_COST

ARG DELEGATE_DELAY=1
ENV DELEGATE_DELAY=$DELEGATE_DELAY

ARG UNDELEGATE_COST=10000
ENV UNDELEGATE_COST=$UNDELEGATE_COST

ARG UNDELEGATE_DELAY=7
ENV UNDELEGATE_DELAY=$UNDELEGATE_DELAY

ARG ERA_DURATION=120
ENV ERA_DURATION=$ERA_DURATION

ARG AUCTION_MANAGER_CONTRACT_HASH=
ENV AUCTION_MANAGER_CONTRACT_HASH=$AUCTION_MANAGER_CONTRACT_HASH

ARG FAUCET_API_URL=
ENV FAUCET_API_URL=$FAUCET_API_URL

ENV STATIC_ROOT=/app/packages/ui/build \
    SERVER_USE_TLS="false" \
    NODE_TLS_REJECT_UNAUTHORIZED=0

ENTRYPOINT node ./packages/server/dist/server.js
