[package]
name = "faucet"
version = "0.1.0"
authors = ["Mateusz Górski <mateusz@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "faucet"
path = "src/bin/main.rs"
doctest = false
test = false
bench = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
casper-contract = "0.7.0"
casper-types = "0.7.0"